# Generated by Django 5.2.9 on 2026-01-13 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('ingreso_mensual', models.FloatField()),
                ('ventas_anuales', models.FloatField(default=0)),
                ('monto_solicitado', models.FloatField()),
                ('plazo_meses', models.IntegerField()),
                ('dias_mora_prom', models.IntegerField(default=0)),
                ('garantia', models.CharField(max_length=20)),
                ('tiene_garante', models.BooleanField(default=False)),
                ('propiedad_completa', models.BooleanField(default=False)),
                ('estado_legal', models.BooleanField(default=False)),
                ('prob_riesgo', models.FloatField()),
                ('prediccion', models.IntegerField()),
                ('recomendacion', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
