# Generated by Django 5.2.9 on 2026-01-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditevaluation',
            name='comentario_analista',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditevaluation',
            name='decision_final',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='creditevaluation',
            name='estado_caso',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('OBSERVADO', 'Observado')], default='PENDIENTE', max_length=12),
        ),
        migrations.AddField(
            model_name='creditevaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='creditevaluation',
            name='recomendacion',
            field=models.CharField(max_length=10),
        ),
    ]
