# Generated by Django 5.2.9 on 2026-01-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_risk', '0002_creditevaluation_comentario_analista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditevaluation',
            name='cliente_apellidos',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='creditevaluation',
            name='cliente_cedula',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='creditevaluation',
            name='cliente_nombres',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
